version: 3
allow:
  depOnAnyVendor: false
  deepScan: false
components:
  main:
    in: .
  proxy:
    in: internal/proxy
  protocol:
    in: internal/protocol
  history:
    in: internal/history
deps:
  main:
    mayDependOn:
      - proxy
  proxy:
    mayDependOn:
      - protocol
      - history
  history:
    mayDependOn:
      - protocol
